# Generated by Django 4.2.1 on 2023-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='Type',
            field=models.CharField(max_length=6),
        ),
    ]
