# Generated by Django 4.2.1 on 2023-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlist', '0002_alter_entry_phone_alter_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='lentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usename', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password_1', models.CharField(max_length=50)),
                ('password_2', models.CharField(max_length=50)),
            ],
        ),
    ]
