# Generated by Django 4.2.1 on 2023-07-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlist', '0003_lentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lentry',
            old_name='Usename',
            new_name='Username',
        ),
    ]
